[project]
name = "syke-pic"
version = "0.6.0"
description = "Plankton image classification with neural networks"
readme = "README.md"
requires-python = ">=3.11, <3.12"
authors = [
    { name = "Otso Velhonoja"},
    { name = "Kaisa Kraft", email = "kaisa.kraft@syke.fi" },
    { name = "Mikko Impiö", email = "mikko.impio@syke.fi" },
]
license = { text = "MIT" }
dependencies = [
    # Pinned because the IFCB feature/biovolume algorithm affects scientific results.
    "ifcb-features @ git+https://github.com/WHOIGit/ifcb-features@v1.3.0",
    "matplotlib>=3.6.3",
    "numpy",
    "opencv-python-headless>=4.5.4.60",
    "pandas>=1.3.3",
    "pyyaml>=6.0.2",
    "scikit-learn>=1.3.2",
    "torch>=2.4.1",
    "torchvision>=0.19.1",
    "tqdm>=4.67.1",
]

[project.urls]
Homepage = "https://github.com/sykefi/syke-pic"

[project.scripts]
sykepic = "sykepic.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["sykepic"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.uv.sources]
ifcb-features = { git = "https://github.com/WHOIGit/ifcb-features", tag = "v1.3.0" }

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
